[tool.poetry]
name = "CoBang"
version = "0.1.0"
description = ""
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
single-version = "^1.1"
xdgenvpy = "^2.3.0"
logbook = "^1.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
PyGObject-stubs = "^0.0.2"
black = {version = "^19.10b0", allow-prereleases = true}

[tool.black]
line-length = 120
target-version = ['py37']
skip-string-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
